# Generated by Django 4.1.3 on 2023-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaNoticia', models.CharField(max_length=200)),
                ('resumoDaNoticia', models.CharField(max_length=200)),
            ],
        ),
    ]
