# Generated by Django 4.1.3 on 2023-06-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='nomeDaNoticia',
            new_name='nome_noticia',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='resumoDaNoticia',
            new_name='resumo_noticia',
        ),
        migrations.AddField(
            model_name='noticia',
            name='url_site',
            field=models.TextField(default=''),
        ),
    ]
